import "~/styles/globals.css";

import Head from "next/head";
import type { AppProps } from "next/app";
import { AppCacheProvider } from "@mui/material-nextjs/v15-pagesRouter";
import { CssBaseline } from "@mui/material";
import { ThemeProvider, createTheme } from "@mui/material/styles";

import { DefaultLayout } from "~/layouts/DefaultLayout";
import { EmotionCache } from "@emotion/cache";

import { createMyEmotionCache } from "../createMyEmotionCache";

const theme = createTheme();

const clientEmotionCache = createMyEmotionCache();

export default function App({
  Component,
  pageProps,
  emotionCache = clientEmotionCache,
}: AppProps & { emotionCache?: EmotionCache }) {
  return (
    <AppCacheProvider emotionCache={emotionCache}>
      <Head>
        <title>pages routerのSSG検証</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={theme}>
        <DefaultLayout>
          <Component {...pageProps} />
        </DefaultLayout>
        <CssBaseline />
      </ThemeProvider>
    </AppCacheProvider>
  );
}
