name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  statuses: write
  deployments: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Next.js SSG
        run: npm run generate

      - name: Deploy to Cloudflare Workers In Production Mode
        if: ${{ github.event_name == 'push' }}
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: "deploy"
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: "4.28.1"

      - name: Alias Deployment URL
        if: ${{ github.event_name == 'pull_request' }}
        id: alias
        run: |
          ALIAS="deploy-preview-${{ github.event.pull_request.number }}--trial-nextjs-pages-ssg.workers.dev"
          echo "host=${ALIAS}" >> $GITHUB_OUTPUT
          echo "url=https://${ALIAS}" >> $GITHUB_OUTPUT

      - name: Deploy to Cloudflare Workers In Preview Mode
        if: ${{ github.event_name == 'pull_request' }}
        id: deploy-preview
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: "versions upload --preview-alias deploy-preview-${{ github.event.pull_request.number }}"
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: "4.28.1"

      - name: Comment Preview URL
        if: ${{ github.event_name == 'pull_request' }}
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            🚀 Deployed to Cloudflare Workers
            Preview URL: ${{ steps.deploy-preview.outputs.pages-deployment-alias-url }}
            <sub>Deployment URL: ${{ steps.deploy-preview.outputs.deployment-url }}</sub>
